services:
#    back.example:
#        class: BackBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BackBundle\Utils\Mailer:
    public: true
    arguments: ["@monolog.logger.mailer"]

  BackBundle\Security\MovieVoter:
    tags:
      - { name: security.voter }

  BackBundle\EventListener\MediaSubscriber:
    public: true
    tags:
      - { name: doctrine.event_subscriber }



