services:
#    back.example:
#        class: BackBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  back_mailer:
    class: BackBundle\Utils\Mailer
    public: true
    arguments: ["@mailer", "@monolog.logger.mailer"]

  back_filter:
    class:  BackBundle\Utils\Filter
    public: true
