services:
#    back.example:
#        class: BackBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  BackBundle\Utils\Mailer:
    public: true
    arguments: ["@mailer", "@monolog.logger.mailer"]
    autowire: true

  BackBundle\Utils\Filter:
    public: true
    autowire: true


